# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160403_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cropping',
            field=image_cropping.fields.ImageRatioField(b'image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=b'profiles/default.png', upload_to=b'profiles'),
        ),
    ]
