# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 19:01
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160407_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=image_cropping.fields.ImageCropField(default=b'profiles/default.png', upload_to=b'profiles'),
        ),
    ]
