# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20160407_1855'),
        ('accounts', '0007_auto_20160407_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_shops',
            field=models.ManyToManyField(related_name='favorite_shops', to='shops.Shop'),
        ),
    ]
