# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160430_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wish_list',
            new_name='wish_products',
        ),
    ]
