# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='background_image',
            field=models.ImageField(default=b'shops_backgrounds/default.png', upload_to=b'shops_backgrounds'),
        ),
    ]
